on: push
name: Lint
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npx
      - name: Run ESLint
        run: eslint .
